### PR TITLE
Compiletime constants exposed

### LINKED ISSUE #129: expose compile time constants
Some compile time constants, such as the max UDP datagram size should be exposed on the lua side to know the details of the lib at runtime.

### PR DESCRIPTION
**Pull request by Tieske**
fixes #129

### CODE REVIEW

**Comment by alerque** [comment]
Is this fix still relevant? The related issue is closed but at least this exact fix doesn't seem to have gone in. Perhaps something comparable did, or is it still unresolved?

**Comment by Tieske** [comment]
This is still relevant imho

**Review by daurnimator — APPROVED** [review]
LGTM

btw, I only now notice that UDP_DATAGRAMSIZE is set to 8192; not the actual max value possible (66535). Should we update the value too?

**Review by alerque — CHANGES_REQUESTED** [review]
This PR predates GitHub's maintainer permissions system for PR updates so only you @Tieske can push either a merge from (or rebase onto) `master` to get current CI checks.

**Comment by Tieske** [comment]
I need to double check the comment by @daurnimator . iirc the original reason for this was Copas, UDP support; https://github.com/lunarmodules/copas/blob/master/src/copas.lua#L26

**Comment by Tieske** [comment]
This is obsolete, was already merged through another PR. The #359 PR holds the final documentation updates.

**Pull request closed without merging**
