### PR TITLE
Add src\compat.c to mime.vcxproj and socket.vcxproj

### PR DESCRIPTION
**Pull request by ewestbrook**
Rebases #231 against current master. Similar change was made to rockspecs in #271.

### CODE REVIEW

**Comment by diegonehab** [comment]
Hmmm. I wonder why I didn't need compat when I tested on Windows. Seems like the kind of thing that would lead to a link error. Have you checked this?

**Comment by ewestbrook** [comment]
I agree, and no, I haven't been able to check it on Windows myself.  Frankly, I'm not sure how it could link at all without it (on Lua 5.1 Windows builds, anyway).  I do know from my own testing that the LuaRocks build was broken until recently because, just like here, `compat` was missing from `mime` and `socket`.  However, that omission didn't come to light until I discovered it during the export pragma work. So perhaps something was obscuring the omission before then, or providing something else in its place until recently.  Wish I could be more helpful under Windows.

**Comment by alerque** [comment]
To any Windows users who make come by...

What purpose exactly do these vcxproj files serve? Is there anyone around that is currently using them that could review this PR sensibly?

**Comment by Tieske** [comment]
the `vcxproj` files are Visual Studio (that is full Visual Studio on Windows, not VS Code) project files, which contain the metadata on how to build a project etc, and all project/solution based settings.

looks fine to me.

**Review by Tieske — APPROVED** [review]

**Comment by diegonehab** [comment]
Do we need the compat module, though?

**Comment by Tieske** [comment]
it defines `luaL_setfuncs` and `luaL_testudata`, which were introduced in Lua 5.2. Both of those are used in multiple places in the codebase (mostly `luaL_setfuncs`)

**Comment by diegonehab** [comment]
Makes sense. I forgot 5.1 is still widely used.

**Pull request merged**
